"""Book model

Revision ID: 38731e80676c
Revises: c626014ba196
Create Date: 2023-03-09 11:00:33.335003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38731e80676c'
down_revision = 'c626014ba196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_pages', sa.Integer(), nullable=False))
        batch_op.drop_column('number_of_page')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_page', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('number_of_pages')

    # ### end Alembic commands ###
